/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ImmutableState } from "../ImmutableState";

export class ImmutableState__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ImmutableState {
    return new Contract(address, _abi, signerOrProvider) as ImmutableState;
  }
}

const _abi = [
  {
    inputs: [],
    name: "factoryV2",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "positionManager",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
