/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IMixedRouteQuoterV1Interface extends ethers.utils.Interface {
  functions: {
    "quoteExactInput(bytes,uint256)": FunctionFragment;
    "quoteExactInputSingleV2(tuple)": FunctionFragment;
    "quoteExactInputSingleV3(tuple)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "quoteExactInput",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteExactInputSingleV2",
    values: [{ tokenIn: string; tokenOut: string; amountIn: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteExactInputSingleV3",
    values: [
      {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      }
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "quoteExactInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteExactInputSingleV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteExactInputSingleV3",
    data: BytesLike
  ): Result;

  events: {};
}

export class IMixedRouteQuoterV1 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IMixedRouteQuoterV1Interface;

  functions: {
    quoteExactInput(
      path: BytesLike,
      amountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "quoteExactInput(bytes,uint256)"(
      path: BytesLike,
      amountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    quoteExactInputSingleV2(
      params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "quoteExactInputSingleV2((address,address,uint256))"(
      params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    quoteExactInputSingleV3(
      params: {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "quoteExactInputSingleV3((address,address,uint256,uint24,uint160))"(
      params: {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  quoteExactInput(
    path: BytesLike,
    amountIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "quoteExactInput(bytes,uint256)"(
    path: BytesLike,
    amountIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  quoteExactInputSingleV2(
    params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "quoteExactInputSingleV2((address,address,uint256))"(
    params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  quoteExactInputSingleV3(
    params: {
      tokenIn: string;
      tokenOut: string;
      amountIn: BigNumberish;
      fee: BigNumberish;
      sqrtPriceLimitX96: BigNumberish;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "quoteExactInputSingleV3((address,address,uint256,uint24,uint160))"(
    params: {
      tokenIn: string;
      tokenOut: string;
      amountIn: BigNumberish;
      fee: BigNumberish;
      sqrtPriceLimitX96: BigNumberish;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    quoteExactInput(
      path: BytesLike,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      amountOut: BigNumber;
      v3SqrtPriceX96AfterList: BigNumber[];
      v3InitializedTicksCrossedList: number[];
      v3SwapGasEstimate: BigNumber;
      0: BigNumber;
      1: BigNumber[];
      2: number[];
      3: BigNumber;
    }>;

    "quoteExactInput(bytes,uint256)"(
      path: BytesLike,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      amountOut: BigNumber;
      v3SqrtPriceX96AfterList: BigNumber[];
      v3InitializedTicksCrossedList: number[];
      v3SwapGasEstimate: BigNumber;
      0: BigNumber;
      1: BigNumber[];
      2: number[];
      3: BigNumber;
    }>;

    quoteExactInputSingleV2(
      params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "quoteExactInputSingleV2((address,address,uint256))"(
      params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    quoteExactInputSingleV3(
      params: {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<{
      amountOut: BigNumber;
      sqrtPriceX96After: BigNumber;
      initializedTicksCrossed: number;
      gasEstimate: BigNumber;
      0: BigNumber;
      1: BigNumber;
      2: number;
      3: BigNumber;
    }>;

    "quoteExactInputSingleV3((address,address,uint256,uint24,uint160))"(
      params: {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<{
      amountOut: BigNumber;
      sqrtPriceX96After: BigNumber;
      initializedTicksCrossed: number;
      gasEstimate: BigNumber;
      0: BigNumber;
      1: BigNumber;
      2: number;
      3: BigNumber;
    }>;
  };

  filters: {};

  estimateGas: {
    quoteExactInput(
      path: BytesLike,
      amountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "quoteExactInput(bytes,uint256)"(
      path: BytesLike,
      amountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    quoteExactInputSingleV2(
      params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "quoteExactInputSingleV2((address,address,uint256))"(
      params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
      overrides?: Overrides
    ): Promise<BigNumber>;

    quoteExactInputSingleV3(
      params: {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "quoteExactInputSingleV3((address,address,uint256,uint24,uint160))"(
      params: {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    quoteExactInput(
      path: BytesLike,
      amountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "quoteExactInput(bytes,uint256)"(
      path: BytesLike,
      amountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    quoteExactInputSingleV2(
      params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "quoteExactInputSingleV2((address,address,uint256))"(
      params: { tokenIn: string; tokenOut: string; amountIn: BigNumberish },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    quoteExactInputSingleV3(
      params: {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "quoteExactInputSingleV3((address,address,uint256,uint24,uint160))"(
      params: {
        tokenIn: string;
        tokenOut: string;
        amountIn: BigNumberish;
        fee: BigNumberish;
        sqrtPriceLimitX96: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
