/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ITokenValidatorInterface extends ethers.utils.Interface {
  functions: {
    "batchValidate(address[],address[],uint256)": FunctionFragment;
    "validate(address,address[],uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "batchValidate",
    values: [string[], string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validate",
    values: [string, string[], BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchValidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validate", data: BytesLike): Result;

  events: {};
}

export class ITokenValidator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ITokenValidatorInterface;

  functions: {
    batchValidate(
      tokens: string[],
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "batchValidate(address[],address[],uint256)"(
      tokens: string[],
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    validate(
      token: string,
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "validate(address,address[],uint256)"(
      token: string,
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  batchValidate(
    tokens: string[],
    baseTokens: string[],
    amountToBorrow: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "batchValidate(address[],address[],uint256)"(
    tokens: string[],
    baseTokens: string[],
    amountToBorrow: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  validate(
    token: string,
    baseTokens: string[],
    amountToBorrow: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "validate(address,address[],uint256)"(
    token: string,
    baseTokens: string[],
    amountToBorrow: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    batchValidate(
      tokens: string[],
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number[]>;

    "batchValidate(address[],address[],uint256)"(
      tokens: string[],
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number[]>;

    validate(
      token: string,
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    "validate(address,address[],uint256)"(
      token: string,
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {};

  estimateGas: {
    batchValidate(
      tokens: string[],
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "batchValidate(address[],address[],uint256)"(
      tokens: string[],
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    validate(
      token: string,
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "validate(address,address[],uint256)"(
      token: string,
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchValidate(
      tokens: string[],
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "batchValidate(address[],address[],uint256)"(
      tokens: string[],
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    validate(
      token: string,
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "validate(address,address[],uint256)"(
      token: string,
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
